# Generated by Django 5.2.6 on 2025-09-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturereview',
            name='rating',
            field=models.SmallIntegerField(),
        ),
    ]
