# Generated by Django 5.2.6 on 2025-09-30 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_activitychathistory_lecturechathistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitychathistory',
            options={'verbose_name': '공모전/대회 챗봇 히스토리', 'verbose_name_plural': '공모전/대회 챗봇 히스토리 목록'},
        ),
        migrations.AlterModelOptions(
            name='lecturechathistory',
            options={'verbose_name': '강의 챗봇 히스토리', 'verbose_name_plural': '강의 챗봇 히스토리 목록'},
        ),
    ]
